[target.arm-unknown-linux-gnueabihf]
# dockerfile = "pibuild.dockerfile"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH", 
  "apt-get update",
  "apt-get -y install libasound2-dev:$CROSS_DEB_ARCH",
]

[build.env]
passthrough = ["PKG_CONFIG_PATH"]
